			var event_dataset = {};

			var skipper = 0;
function addevent2(title,ebid,text,cert,natural_distance,position){
	skipper += 1;
	if (skipper > 5) { skipper = 0; }
	else { return; }
	x = position * 160 - 70;
	if (x > 500){ x += 160; }	
	if (x > 1200){ x -= 500; }	
	newevent = {'ebid': ebid, 'title': title, 'natural_distance': natural_distance, 'text':text, 'who':'', 'height':200, 'width':150, 'x':x };
	event_dataset[ebid] = newevent;
}
		addevent2(' 15 December 1849 ','tt125',' The weekly Domestic Journal and Home Miscellany of Instruction and Amusement ended publication in London. ',' CERT ','24','3');
		addevent2(' 10 December 1849 ','tt124',' Marian Rebecca Hughes received approval to found the Anglican Society of the Holy and Undivided Trinity in Little St Edward`s, West Malvern, Worcestershire. ',' CERT ','24','2');
		addevent2(' December 1849 ','tt123',' Thomas Carlyle published his racist Occasional Discourse on the Negro Question in Fraser`s. ',' CERT ','24','1');
		addevent2(' 13 November 1849 ','tt122',' William Etty died: a genre painter, Etty was one few English artists of his time to concentrate almost exclusively on nudes. ',' CERT ','23','1');
		addevent2(' 9 October 1849 ','tt121',' Rufus Griswold (later editor and publicist of Edgar Allan Poe) published Poe`s now-famous poem Annabel Lee in the New York Daily Tribune in an obituary two days after the author`s mysterious death. ',' CERT ','22','1');
		addevent2(' 13 August 1849 ','tt120',' Hungary was reconquered for the Hapsburgs when the Hungarian army surrendered to the Russian commander. ',' CERT ','20','2');
		addevent2(' August 1849 ','tt119',' Austrian troops conquered the Venetian Republic after a four-month siege, during which thousands of Venetians died. ',' CERT ','20','1');
		addevent2(' 28 July 1849 ','tt118',' An Act to Protect Women Under Twenty-One From Fraudulent Practices to Procure Their Defilement was passed; the act was ineffectual and not enforced. ',' CERT ','19','4');
		addevent2(' 28 July 1849 ','tt117',' The Encumbered Estates Act began to rationalize Irish land titles, in a move towards English-style capitalist land ownership. ',' CERT ','19','3');
		addevent2(' 26 July 1849 ','tt116',' A convention at Kingston, Ontario, proposed annexing Canada with the US, following a depression caused by the loss of Canadian economic preference in the UK. ',' CERT ','19','2');
		addevent2(' 7 July 1849 ','tt115',' George Meredith`s first published work, the poem Chillianwallah, appeared in Chambers`s Edinburgh Journal. ',' CERT ','19','1');
		addevent2(' 30 June 1849 ','tt114',' A weekly periodical for women entitled The Domestic Journal and Home Miscellany of Instruction and Amusement began publication in London. ',' CERT ','18','4');
		addevent2(' 23 June 1849 ','tt113',' Louisa Nottidge`s relatives were were put on trial for confining her against her will in a lunatic asylum; she was awarded ¥50 damages. ',' CERT ','18','3');
		addevent2(' June 1849 ','tt112',' The actress Anna Cora Mowatt`s play Armand; or, the Peer and the Peasant opened at the Marylebone Theatre. ',' CERT ','18','2');
		addevent2(' June 1849 ','tt111',' The Italian revolution was suppressed in Rome, where armies of by now non-revolutionary France (sent to protect the Pope) besieged and reconquered the city. ',' CERT ','18','1');
		addevent2(' 10 May 1849 ','tt110',' John Ruskin published The Seven Lamps of Architecture, a seminal text for the Arts and Crafts movement. ',' CERT ','17','3');
		addevent2(' May 1849 ','tt109',' The Royal Academy exhibition featured the first Pre-Raphaelite works by William Holman Hunt and John Everett Millais. ',' CERT ','17','2');
		addevent2(' By May 1849 ','tt108',' With the help of Swiss mercenaries, Ferdinand II reconquered Sicily and reinforced his rule in Naples. ',' BY ','17','1');
		addevent2(' 1849 ','tt107',' The first bombing raid from the air occurred when a pilotless Montgolfier balloon was used to drop bombs on Venice. ',' AFTER ','16','5');
		addevent2(' 25 April 1849 ','tt106',' The Parliament Buildings in Lower Canada were burned in a riot in Montreal following the signing of the Rebellion Losses Bill. ',' CERT ','16','4');
		addevent2(' 14 April 1849 ','tt105',' Hungary, under the revolutionary leadership of Louis Kossuth, became an autonomous reformed state, deposing the Austrian Emperor Francis Joseph. ',' CERT ','16','3');
		addevent2(' 3 April 1849 ','tt104',' Frederick William IV`s refusal of the imperial crown of Germany signalled the end of the Frankfurt Assembly, which collapsed in December 1849. ',' CERT ','16','2');
		addevent2(' Spring1849 ','tt103',' Dante Gabriel Rossetti`s painting The Girlhood of Mary Virgin (featuring Christina Rossetti as its model) appearing at the Free Exhibition at Hyde Park Gallery, was the first to display the initials of the Pre-Raphaelite Brotherhood. ',' C ','16','1');
		addevent2(' 28 March 1849 ','tt102',' The Frankfurt Assembly elected Prussia`s King Frederick William IV as Emperor of Germany. ',' CERT ','15','3');
		addevent2(' March 1849 ','tt101',' Having been defeated by the Austrians at Novara, Charles Albert abdicated the throne of Piedmont; he was succeeded by Victor Emmanuel II. ',' CERT ','15','2');
		addevent2(' March 1849 ','tt100',' The Select Committee on Public Libraries was appointed; William Ewart, chair, worked closely with Edward Edwards to write the report that became the basis for the Public Libraries Bill of February 1850. ',' CERT ','15','1');
		addevent2(' February 1849 ','tt99',' Matthew Arnold published his first volume of poetry, The Strayed Reveller, and Other Poems, anonymously under the initial A. ',' CERT ','14','1');
		addevent2(' 29 January 1849 ','tt98',' The National Parliamentary and Financial Reform Association was founded to unite Chartists and radicals. ',' CERT ','13','3');
		addevent2(' By 6 January 1849 ','tt97',' William Harrison Ainsworth`s historical novel The Lancashire Witches: A Romance of Pendle Forest appeared in volume form. ',' BY ','13','2');
		addevent2(' January 1849 ','tt96',' Radicals ascended to power in Rome (centre of the Papal States) and established a Roman Republic. ',' CERT ','13','1');
		addevent2(' 20 December 1848 ','tt95',' The New Zealand legislature was opened by the Governor. ',' CERT ','12','6');
		addevent2(' 10 December 1848 ','tt94',' By an overwhelming majority, the French elected Louis Napoleon (the nephew of the Emperor) under the slogan No more taxes, down with the rich, down with the Republic, long live the Emperor.40 ',' CERT ','12','5');
		addevent2(' About 9 December 1848 ','tt93',' Thomas Babington Macaulay published the first two volumes of his History of England. ',' C ','12','4');
		addevent2(' 2 December 1848 ','tt92',' Emperor-King Ferdinand I of Austria abdicated in favour of his nephew Francis Joseph. ',' CERT ','12','3');
		addevent2(' December 1848 ','tt91',' Edgar Allan Poe published The Poetic Principle in The Southern Literary Messenger after presenting it as a successful public lecture in Providence earlier in December. ',' CERT ','12','2');
		addevent2(' December 1848 ','tt90',' Arthur Hugh Clough published The Bothie of Tober-na-Fuosich, later reprinted as The Bothie of Tober-na Vuolich. ',' CERT ','12','1');
		addevent2(' Late 1848 ','tt89',' Following the death on 18 November of Charles Heath, engraver and publisher, the annual Heath`s Book of Beauty became the Book of Beauty or Royal Gallery; however, it soon ceased publication. ',' AFTER ','11','2');
		addevent2(' Early November 1848 ','tt88',' Frederick William IV of Prussia replaced his liberal ministers with a conservative government which adjourned the Constituent Assembly. ',' C ','11','1');
		addevent2(' 31 October 1848 ','tt87',' 4,000 people were killed in Vienna when the Imperial government reconquered the city following what is variously called by historians the second revolution and the third rising. ',' CERT ','10','4');
		addevent2(' 16 October 1848 ','tt86',' Priscilla Lydia Sellon founded the Church of England Sisterhood of Mercy of Devonport and Plymouth in Exeter. ',' CERT ','10','3');
		addevent2(' 6 October 1848 ','tt85',' Imperial troops clashed with Viennese radicals, beginning the so-called second revolution. ',' CERT ','10','2');
		addevent2(' By 23 September 1848 ','tt84',' A volume of fourteen Poems by a Sempstress, published by E. L. E., called for just and equal brotherhood.1091 (1848): 957 ',' BY ','9','2');
		addevent2(' 4 September 1848 ','tt83',' A UK order in council made Cape Colony a penal settlement. ',' CERT ','9','1');
		addevent2(' Autumn1848 ','tt82',' The Pre-Raphaelite Brotherhood was founded in rebellion against the constraints and techniques of art as practised by the Royal Academy. ',' C ','10','1');
		addevent2(' 31 August 1848 ','tt81',' The Public Health Act was passed, establishing the new General Board of Health as a first step towards a strong national health authority in Britain. ',' CERT ','8','4');
		addevent2(' 14 August 1848 ','tt80',' The Act of Union (Upper and Lower Canada) was amended to repeal the clause which declared English the sole official language. ',' CERT ','8','3');
		addevent2(' 9 August 1848 ','tt79',' Captain Frederick Marryat, novelist and father of Florence Marryat, died at Langham, Norfolk. ',' CERT ','8','2');
		addevent2(' August 1848 ','tt78',' American William Henry Lane, Master Juba, arrived in England; his exceptional dancing skills brought him fame and popularity in Britain as in the States. ',' C ','8','1');
		addevent2(' 28 July 1848 ','tt77',' Frederick Douglass in The North Star reported—and praised—the recent women`s rights convention at Seneca Falls, New York. ',' CERT ','7','9');
		addevent2(' July 1848 ','tt76',' Austrian troops restored the Grand Duke to his throne in Tuscany, having successfully suppressed the republic there. ',' C ','7','8');
		addevent2(' 19 July 1848 ','tt75',' The first women`s rights convention in the United States met in Seneca Falls, New York. ',' C ','7','7');
		addevent2(' 18 July 1848 ','tt74',' The Sisters of St John`s House was established at King`s College Hospital for the newly founded Anglican nursing order, the Community of Nursing Sisters of St John the Divine. ',' CERT ','7','6');
		addevent2(' Summer1848 ','tt73',' The Female School of Design was abruptly moved to 330 The Strand, near Drury Lane. ',' C ','7','5');
		addevent2(' July 1848 ','tt72',' After a fierce struggle, Austrian general Radetzky regained control of Milan, from which he had retreated four months earlier. ',' CERT ','7','4');
		addevent2(' July 1848 ','tt71',' Charles Albert of Piedmont negotiated a short-lived Italian union between the territories of Piedmont and Lombardy, Venice, Parma, Modena, and Lucca. ',' CERT ','7','3');
		addevent2(' July 1848 ','tt70',' In the shadow of the Great Famine, the Young Irelanders staged a revolt or rebellion against British rule and suffered ignominious defeat. ',' CERT ','7','2');
		addevent2(' 1 July 1848 ','tt69',' John Cassell established the publishing firm of John Cassell in London with the first issue of a weekly newspaper, the Standard of Freedom. ',' CERT ','7','1');
		addevent2(' June 1848 ','tt68',' The radical Douglas Jerrold`s Shilling Magazine ceased publication, though Douglas Jerrold`s Weekly Newspaper continued under various titles until May 1851. ',' CERT ','6','6');
		addevent2(' June 1848 ','tt67',' Serbs in southern Hungary revolted against the new Hungarian government. ',' CERT ','6','5');
		addevent2(' June 1848 ','tt66',' The Habsburg army put down a radical insurrection in Prague. ',' CERT ','6','4');
		addevent2(' June 1848 ','tt65',' Widespread arrests of Chartist leaders followed uprisings in protest of the rejection of the third petition for universal suffrage. ',' CERT ','6','3');
		addevent2(' Summer1848 ','tt64',' After an abortive Bradford rising,183 local women mounted a kind of charivari to punish a witness against local Chartists. ',' C ','6','2');
		addevent2(' Summer1848 ','tt63',' A National Victim Fund was established to deal with the effects of increased government intolerance of Chartism. ',' C ','6','1');
		addevent2(' About May 1848 ','tt62',' Czechoslovakians claimed nationhood when their spokesman refused to participate in the Frankfurt parliament at the invitation of German liberals. ',' UNKNOWN ','5','3');
		addevent2(' May 1848 ','tt61',' Charles Albert of Piedmont defeated the Austrians at Goito. ',' CERT ','5','2');
		addevent2(' 1 May 1848 ','tt60',' Queen`s College for Women (a secondary, not a post-secondary institution) was founded in London to educate prospective governesses and improve girls` education generally. ',' CERT ','5','1');
		addevent2(' Easter 1848 ','tt59',' The Anglican Community of St Mary the Virgin was founded after this festival by William John Butler, with Elizabeth Lockhart as mother superior, in Wantage, Berkshire. ',' AFTER ','4','8');
		addevent2(' 25 April 1848 ','tt58',' A constitution for the entire Austrian Empire was proclaimed in Vienna; among its provisions was the abolition of serfdom. ',' CERT ','4','7');
		addevent2(' 24 April 1848 ','tt57',' The People`s League was founded. ',' CERT ','4','6');
		addevent2(' 13 April 1848 ','tt56',' The House of Commons rejected the third petition for universal manhood suffrage. ',' C ','4','5');
		addevent2(' 10 April 1848 ','tt55',' A huge demonstration was held at Kennington Common in support of the Chartist National Petition which was to be submitted to parliament. ',' CERT ','4','4');
		addevent2(' By 1 April 1848 ','tt54',' Charles Kingsley published The Saint`s Tragedy, a blank verse drama on the life of St Elizabeth of Hungary. ',' BY ','4','3');
		addevent2(' Spring1848 ','tt53',' Following a tour of inspection of working class housing, Prince Albert assumed a more active role in his presidency of the Society for Improving the Condition of the Labouring Classes. ',' C ','4','2');
		addevent2(' April 1848 ','tt52',' In France, universal manhood suffrage enabled a politically inexperienced peasantry to elect a minority of monarchists, but sent a large majority of conservatives to Paris. ',' C ','4','1');
		addevent2(' After March 1848 ','tt51',' The Austrian nationalist uprising was overthrown by General Radetzky. ',' AFTER ','3','11');
		addevent2(' 24 March 1848 ','tt50',' King Charles Albert of Piedmont declared war on Austria; the outcome was his abdication. ',' CERT ','3','10');
		addevent2(' 22 March 1848 ','tt49',' London moderates formed the People`s Charter Union, aiming to obtain the Charter by peaceable means. ',' CERT ','3','9');
		addevent2(' 21 March 1848 ','tt48',' Frederick William IV committed himself to German nationalism and unification, promising to summon a Constituent Assembly to create a united Prussian Diet, which in turn would consider establishing a national German parliament. ',' CERT ','3','8');
		addevent2(' 18 March 1848 ','tt47',' The unemployed rioted in Berlin, the capital of Prussia. ',' CERT ','3','7');
		addevent2(' 13 March 1848 ','tt46',' A revolution took place in Vienna, where protesters—both students and urban working-class people—successfully urged the Emperor Ferdinand to dismiss Clemens Von Metternich. ',' CERT ','3','6');
		addevent2(' 6 March 1848 ','tt45',' A revolution occurred in Bavaria. Another took place in Berlin on the 11th. ',' CERT ','3','5');
		addevent2(' 2 March 1848 ','tt44',' A revolution began in south-west Germany, where the Grand Duchy of Baden`s population demonstrated against the Metternich System and the Carlsbad Decrees. ',' CERT ','3','4');
		addevent2(' March 1848 ','tt43',' Six men were killed when troops opened fire on riots against the Poor Law in Glasgow. ',' C ','3','3');
		addevent2(' March 1848 ','tt42',' Germany and Denmark clashed over Schleswig-Holstein. ',' CERT ','3','2');
		addevent2(' March 1848 ','tt41',' Chartist uprisings took place in London, Glasgow, and Manchester. ',' CERT ','3','1');
		addevent2(' 24 February 1848 ','tt40',' The Second Republic was declared in France after Louis-Philippe abdicated and fled to England. ',' CERT ','2','6');
		addevent2(' 23 February 1848 ','tt39',' Fourteen-year-old Fleeming Jenkin (son of the writer Henrietta Camilla Jenkin and a future distinguished scientist), caught up in the February Revolution, noted the number and variety of women among the street mobs. ',' CERT ','2','5');
		addevent2(' 23 February 1848 ','tt38',' Eminent radicals hosted a ceremony for William Lovett. ',' CERT ','2','4');
		addevent2(' 21 February 1848 ','tt37',' Friedrich Engels and Karl Marx published their Manifesto of the Communist Party, often known as the Communist Manifesto. ',' CERT ','2','3');
		addevent2(' February 1848 ','tt36',' Tuscany was granted a constitution by its Grand Duke. ',' CERT ','2','2');
		addevent2(' February 1848 ','tt35',' Riots occurred in Munich when students protested Ludwig I`s association with Lola Montez, a Scottish dancer. ',' CERT ','2','1');
		addevent2(' 29 January 1848 ','tt34',' Insurgency in Sicily resulted in the declaration of Sicily`s independence and the granting on this date, by Ferdinand II of Naples, of a constitution. ',' CERT ','1','4');
		addevent2(' 24 January 1848 ','tt33',' The discovery of gold at Sutter`s Creek, California, led to the first gold rush (which is popularly named from the year following this one). ',' CERT ','1','3');
		addevent2(' By January 1848 ','tt32',' Most railway companies in Britain had adopted Greenwich Mean Time or GMT (measured at the Royal Observatory at Greenwich), as had been recommended on 22 September 1847. ',' BY ','1','2');
		addevent2(' 1 January 1848 ','tt31',' The first issue appeared of the Rambler, a controversial periodical aimed at Roman Catholics and recent converts. ',' CERT ','1','1');
		addevent2(' December 1847 ','tt30',' Frederick Douglass launched his anti-slavery periodical, North Star, in Rochester, New York, substantially aided by British abolitionist women. ',' BY ','0','1');
		addevent2(' 15 November 1847 ','tt29',' Dr James Young Simpson of Edinburgh published a pamphlet describing how he had proved in practice that chloroform was a successful anaesthetic for obstetrics; his pamphlet sold 1,500 copies within fourteen days. ',' CERT ','-1','2');
		addevent2(' November 1847 ','tt28',' Alfred Tennyson published The Princess: A Medley. ',' CERT ','-1','1');
		addevent2(' By 18 September 1847 ','tt27',' John Conolly published The Construction and Government of Lunatic Asylums and Hospitals for the Insane, which likened the asylum to a home with a benevolent superintendent father. ',' BY ','-3','3');
		addevent2(' 4 September 1847 ','tt26',' The printing firm Messrs Biggar and Odhams was founded by William Biggar and William Odhams at 15 Beaufort Buildings, London. ',' CERT ','-3','2');
		addevent2(' September 1847 ','tt25',' The Vegetarian Society was founded in Ramsgate, Kent. ',' CERT ','-3','1');
		addevent2(' 17 August 1847 ','tt24',' The duchesse de Praslin was murdered by her husband in their home in Paris. He attempted to conceal his guilt, then took poison and died during his trial. ',' CERT ','-4','2');
		addevent2(' August 1847 ','tt23',' As a result of the famine, three million Irish were being served by government-sponsored soup kitchens; the programme was halted without notice in September, forcing 200,000 into workhouses. ',' CERT ','-4','1');
		addevent2(' 1 July 1847 ','tt22',' A British government enquiry into the state of education in Wales by commissioners R. R. W. Lingen, Jellynger C. Symons, and H. R. Vaughan Johnson presented a report in three massive volumes. ',' CERT ','-5','2');
		addevent2(' July 1847 ','tt21',' Feargus O`Connor, the only Chartist Member of Parliament ever, was returned for Nottingham at a general election in which Chartism was an important issue. ',' CERT ','-5','1');
		addevent2(' 8 June 1847 ','tt20',' The Irish Poor Law Extension Act was passed. ',' CERT ','-6','4');
		addevent2(' 8 June 1847 ','tt19',' A Factory Act, also known as The Ten Hours Act, restricted the length of British women`s and teenagers` working day in textile factories to ten hours. ',' CERT ','-6','3');
		addevent2(' By 5 June 1847 ','tt18',' Leigh Hunt published Men, Women, and Books. ',' BY ','-6','2');
		addevent2(' Summer1847 ','tt17',' Liberal Protestants defeated conservative Catholics in a civil war in Switzerland. ',' C ','-6','1');
		addevent2(' By 15 May 1847 ','tt16',' Anthony Trollope published his first novel, The Macdermots of Ballycloran. ',' BY ','-7','5');
		addevent2(' 15 May 1847 ','tt15',' The death of Daniel O`Connell (in Genoa in the course of a pilgrimage to Rome for his failing health) left Irish politics in disarray. ',' CERT ','-7','4');
		addevent2(' 4 May 1847 ','tt14',' Jenny Lind, the Swedish Nightingale, gave her first London performance at Her Majesty`s Theatre. ',' CERT ','-7','3');
		addevent2(' May 1847 ','tt13',' David Joy designed a popular high-pressure engine; the first one of which was called Jenny Lind after the popular singer, leading these locomotives to be known as Jennies. ',' CERT ','-7','2');
		addevent2(' Early 1847 ','tt12',' John Mitchell founded the United Irishman, a publication advocating armed rebellion against British rule. ',' BY ','-7','1');
		addevent2(' Early 1847 ','tt11',' Canterbury established the first rate-aided library in England. ',' BY ','-8','5');
		addevent2(' By 24 April 1847 ','tt10',' Captain Frederick Marryat published Children of the New Forest, his last and most popular novel. ',' BY ','-8','4');
		addevent2(' 6 April 1847 ','tt9',' Covent Garden Theatre re-opened (with a performance of Rossini`s Semiramide) as The Royal Italian Opera, Covent Garden. ',' CERT ','-8','3');
		addevent2(' April 1847 ','tt8',' Adams and Company of London patented the first double decker bus. ',' CERT ','-8','2');
		addevent2(' April 1847 ','tt7',' Two of Elizabeth Fry`s daughters, Katherine Fry and R. E. Cresswell, completed their account of the activist`s life in the two-volume Memoir of the Life of Elizabeth Fry; with Extracts from Her Journals and Letters. ',' CERT ','-8','1');
		addevent2(' March 1847 ','tt6',' Benjamin Disraeli published his novel Tancred. ',' CERT ','-9','3');
		addevent2(' Early 1847 ','tt5',' Angry rioters in Berlin, Hamburg, and other cities in Germany protested high prices by attacking bakeries and storehouses. ',' BY ','-9','2');
		addevent2(' Spring1847 ','tt4',' 750,000 men were employed in Ireland`s public works, in a policy designed to relieve the distress caused by repeated crop failures (particularly of potatoes). ',' C ','-9','1');
		addevent2(' 17 February 1847 ','tt3',' The Whittington Club (named after the poor boy who became Lord Mayor of London) held its first meeting. Unlike traditional gentlemen`s clubs, it welcomed women and lower-middle-class men. ',' CERT ','-10','2');
		addevent2(' February 1847 ','tt2',' William F. Thomas, a corset manufacturer in Cheapside, bought the English rights to Elias Howe`s sewing machine; their subsequent partnership resulted in the first sewing machines made in England. ',' CERT ','-10','1');
		addevent2(' 2 January 1847 ','tt1',' The weekly Lady`s Newspaper and Pictorial Times began publication in London. ',' CERT ','-11','2');
		addevent2(' January 1847 ','tt0',' Fatality, a play written by Caroline Boaden, premiered at the Olympic Theatre. ',' CERT ','-11','1');